package org.usfirst.frc.team694.robot;

/**
 * FieldMap contains the field measurements that we use in our autons.
 * All of our autons should be based on the field so that if our measurements 
 * change, we can adapt quickly. All measurements are in inches for encoder purposes.
 */
public final class FieldMapQuadrant1 {

/* Given FRC Manual Measurements*/
    //These distances is us starting on the left side of the field
    //all measurements are in inches or degrees if specified 
    //anything with // could be changed due to the actual field measure 
    
    //These are the measurements that need to be measured out before match.
    public static final double QUADRANT_1_DISTANCE_FROM_BORDER_TO_MIDDLE_OF_FIELD = 162.0; //
    public static final double QUADRANT_1_DISTANCE_FROM_PLATFORM_ZONE_EDGE_TO_BUMP = 66.75; //
    public static final double QUADRANT_1_DISTANCE_FROM_ALLIANCE_STATION_TO_MIDDLE_OF_SWITCH = 168.0; //
    public static final double QUADRANT_1_DISTANCE_FROM_ALLIANCE_STATION_TO_NULL_TERRITORY = 288.0; //
    public static final double QUADRANT_1_DISTANCE_FROM_ALLIANCE_STATION_TO_AUTO_LINE = 120.0; //
    public static final double QUADRANT_1_DISTANCE_FROM_ALLIANCE_STATION_TO_SWITCH = 140.0; //
    public static final double QUADRANT_1_DISTANCE_FROM_ALLIANCE_STATION_TO_FAR_SIDE_OF_SWITCH = 196.0; //
    public static final double QUADRANT_1_DISTANCE_FROM_ALLIANCE_STATION_TO_PLATFORM_EDGE = 261.47; //
    public static final double QUADRANT_1_DISTANCE_FROM_ALLIANCE_STATION_TO_SCALE_SIDE = 299.65; //
    public static final double QUADRANT_1_DISTANCE_FROM_NULL_TERRITORY_TO_NULL_BUMP = 36.0; //
    public static final double QUADRANT_1_DISTANCE_FROM_BORDER_TO_SWITCH_EDGE = 85.25; //
    public static final double QUADRANT_1_DISTANCE_FROM_BORDER_TO_PLATFORM_ZONE_EDGE = 95.25; //
    public static final double QUADRANT_1_DISTANCE_FROM_BORDER_TO_EDGE_OF_ROBOT = 29.69; //
  //public static final double QUADRANT_1_DISTANCE_FROM_NULL_BUMP_TO_AUTO_LINE = 204.0; //
    
    //**************************************************************************************************************
    
    public static final double QUADRANT_1_DISTANCE_FROM_BORDER_TO_OTHER_EDGE_OF_ROBOT = QUADRANT_1_DISTANCE_FROM_BORDER_TO_EDGE_OF_ROBOT + FieldMap.WIDTH_OF_BOT;
    public static final double QUADRANT_1_DISTANCE_FROM_BORDER_TO_ROBOT_STARTING_POINT = QUADRANT_1_DISTANCE_FROM_BORDER_TO_EDGE_OF_ROBOT + FieldMap.MIDDLE_OF_BOT_WIDTHWISE; //
    
    public static final double QUADRANT_1_DISTANCE_FROM_SCALE_SIDE_TO_NULL_TERRITORY = QUADRANT_1_DISTANCE_FROM_ALLIANCE_STATION_TO_SCALE_SIDE - QUADRANT_1_DISTANCE_FROM_ALLIANCE_STATION_TO_NULL_TERRITORY;
    public static final double QUADRANT_1_DISTANCE_FROM_FAR_SIDE_OF_SWITCH_TO_SCALE_SIDE = QUADRANT_1_DISTANCE_FROM_ALLIANCE_STATION_TO_SCALE_SIDE - QUADRANT_1_DISTANCE_FROM_ALLIANCE_STATION_TO_FAR_SIDE_OF_SWITCH;

    public static final double QUADRANT_1_DISTANCE_FROM_LINE_SENSOR_TO_AUTO_LINE = QUADRANT_1_DISTANCE_FROM_ALLIANCE_STATION_TO_AUTO_LINE - (FieldMap.LENGTH_OF_BOT - FieldMap.DISTANCE_LINE_SENSOR_IS_FROM_FRONT_BUMPER_OF_BOT);
   
    //**************************************************************************************************************
    //Scale auton where the bot is on the same side as the alliance scale and bot will be in the null territory
    public static final double QUADRANT_1_DISTANCE_FROM_NULL_BUMP_TO_AUTO_LINE = 204.0; //
    public static final double QUADRANT_1_DISTANCE_TO_MOVE_INTO_NULL_BUMP = FieldMap.MIDDLE_OF_BOT_LENGTHWISE - FieldMap.DISTANCE_LINE_SENSOR_IS_FROM_FRONT_BUMPER_OF_BOT;
    public static final double QUADRANT_1_DISTANCE_TO_TRAVEL_BACKWARDS = QUADRANT_1_DISTANCE_FROM_BORDER_TO_EDGE_OF_ROBOT - FieldMap.DIFFERENCE_BETWEEN_LENGTH_OF_ROBOT_AND_WIDTH_OF_ROBOT_AFTER_TURN; 
    public static final double QUADRANT_1_DISTANCE_TO_TRAVEL_TO_REACH_SCALE_EDGE = QUADRANT_2_DISTANCE_FROM_BORDER_TO_SCALE_EDGE - FieldMap.LENGTH_OF_BOT;
    
    //Scale auton where the bot is on the same side as the alliance scale and bot will turn at null territory line
    public static final double QUADRANT_1_DISTANCE_FROM_AUTO_LINE_TO_NULL_TERRITORY = QUADRANT_1_DISTANCE_FROM_ALLIANCE_STATION_TO_NULL_TERRITORY - QUADRANT_1_DISTANCE_FROM_ALLIANCE_STATION_TO_AUTO_LINE;
    public static final double QUADRANT_1_DISTANCE_FROM_SCALE_EDGE_TO_MIDDLE_OF_ROBOT = QUADRANT_2_DISTANCE_FROM_BORDER_TO_SCALE_EDGE - QUADRANT_1_DISTANCE_FROM_BORDER_TO_ROBOT_STARTING_POINT;
    public static final double QUADRANT_1_DISTANCE_FROM_SCALE_EDGE_TO_MIDDLE_OF_ROBOT_SQUARED = QUADRANT_1_DISTANCE_FROM_SCALE_EDGE_TO_MIDDLE_OF_ROBOT * QUADRANT_1_DISTANCE_FROM_SCALE_EDGE_TO_MIDDLE_OF_ROBOT;
    public static final double QUADRANT_1_DISTANCE_FROM_SCALE_SIDE_TO_NULL_TERRITORY_SQUARED = QUADRANT_1_DISTANCE_FROM_SCALE_SIDE_TO_NULL_TERRITORY * QUADRANT_1_DISTANCE_FROM_SCALE_SIDE_TO_NULL_TERRITORY;
    public static final double QUADRANT_1_DISTANCE_TO_TRAVEL_TO_REACH_SCALE_CORNER = Math.sqrt(QUADRANT_1_DISTANCE_FROM_SCALE_EDGE_TO_MIDDLE_OF_ROBOT_SQUARED + QUADRANT_1_DISTANCE_FROM_SCALE_SIDE_TO_NULL_TERRITORY_SQUARED);
    public static final double QUADRANT_1_DEGREE_OF_ANGLE_TO_REACH_IDEAL_STARTING_POdouble_FROM_NULL_TERRITORY_LINE = -1 * Math.toDegrees(Math.atan(QUADRANT_1_DISTANCE_FROM_SCALE_EDGE_TO_MIDDLE_OF_ROBOT / QUADRANT_1_DISTANCE_FROM_SCALE_SIDE_TO_NULL_TERRITORY));
    
    //Scale auton where the bot is on the other side of the alliance scale
    public static final double QUADRANT_1_DISTANCE_FROM_AUTO_LINE_TO_FAR_SIDE_OF_SWITCH = QUADRANT_1_DISTANCE_FROM_ALLIANCE_STATION_TO_FAR_SIDE_OF_SWITCH - QUADRANT_1_DISTANCE_FROM_ALLIANCE_STATION_TO_AUTO_LINE;
    public static final double QUADRANT_1_DISTANCE_FROM_FAR_SIDE_OF_SWITCH_TO_PLATFORM_EDGE = QUADRANT_1_DISTANCE_FROM_ALLIANCE_STATION_TO_PLATFORM_EDGE - QUADRANT_1_DISTANCE_FROM_ALLIANCE_STATION_TO_FAR_SIDE_OF_SWITCH;
    public static final double QUADRANT_1_DISTANCE_FROM_FAR_SIDE_OF_SWITCH_TO_PLATFORM_EDGE_HALVED = QUADRANT_1_DISTANCE_FROM_FAR_SIDE_OF_SWITCH_TO_PLATFORM_EDGE / 2;
    public static final double QUADRANT_1_DISTANCE_TO_TRAVEL_BEFORE_FIRST_TURN_FROM_AUTO_LINE = QUADRANT_1_DISTANCE_FROM_AUTO_LINE_TO_FAR_SIDE_OF_SWITCH + QUADRANT_1_DISTANCE_FROM_FAR_SIDE_OF_SWITCH_TO_PLATFORM_EDGE_HALVED + (FieldMap.MIDDLE_OF_BOT_LENGTHWISE - FieldMap.DISTANCE_LINE_SENSOR_IS_FROM_FRONT_BUMPER_OF_BOT); 
    public static final double QUADRANT_1_DISTANCE_TO_TRAVEL_TO_REACH_PLATFORM_ZONE_EDGE = (QUADRANT_1_DISTANCE_FROM_BORDER_TO_PLATFORM_ZONE_EDGE - (QUADRANT_1_DISTANCE_FROM_BORDER_TO_OTHER_EDGE_OF_ROBOT + FieldMap.DIFFERENCE_BETWEEN_LENGTH_OF_ROBOT_AND_WIDTH_OF_ROBOT_AFTER_TURN)) + FieldMap.DISTANCE_LINE_SENSOR_IS_FROM_FRONT_BUMPER_OF_BOT;
    public static final double QUADRANT_1_DISTANCE_TO_DRIVE_OUT_AFTER_PLATFORM_ZONE = FieldMap.WIDTH_OF_BOT - FieldMap.DISTANCE_LINE_SENSOR_IS_FROM_FRONT_BUMPER_OF_BOT; 
    public static final double QUADRANT_1_DISTANCE_TO_TRAVEL_TO_REACH_SCALE_SIDE = QUADRANT_6_DISTANCE_FROM_FAR_SIDE_OF_SWITCH_TO_SCALE_SIDE - QUADRANT_6_DISTANCE_FROM_FAR_SIDE_OF_SWITCH_TO_PLATFORM_EDGE_HALVED;
}