package org.usfirst.frc.team694.robot;

/**
 * FieldMap contains the field measurements that we use in our autons.
 * All of our autons should be based on the field so that if our measurements 
 * change, we can adapt quickly. All measurements are in inches for encoder purposes.
 */
public final class FieldMapSideFurthestFromScoringTableBlueQuadrant implements FieldMapInterface{
    //Scale auton where the bot and the scoring scale are on the same side
    @Override
    public double getTotalDistanceToTravelToReachNullLine() {
        return SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_TOTAL_DISTANCE_TO_TRAVEL_TO_REACH_NULL_TERRITORY_LINE;
    }

    @Override
    public double getDegreeOfAngleToReachIdealStartingPointFromNullTerritoryLine() {
        return SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DEGREE_OF_ANGLE_TO_REACH_IDEAL_STARTING_POINT_FROM_NULL_TERRITORY_LINE;
    }

    @Override
    public double getDistanceToTravelToReachScaleCorner() {
        return SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_TO_TRAVEL_TO_REACH_SCALE_CORNER;
    }

    //Scale auton where the bot and the scoring scale are on different sides
    @Override
    public double getTotalDistanceToTravelBeforeTurn() {
        return SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_TOTAL_DISTANCE_TO_TRAVEL_BEFORE_FIRST_TURN;
    }

    @Override
    public double getDistanceFromLineSensorToAutoLine() {
        return SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_LINE_SENSOR_TO_AUTO_LINE;
    }

    @Override
    public double getDegreeOfAngleToTurnToReachPlatformZone() {
        return SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DEGREE_OF_ANGLE_TO_TURN_TO_REACH_PLATFORM_ZONE;
    }

    @Override
    public double getTotalDistanceToTravelToReachOtherSideOfPlatformZone() {
        return SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_TOTAL_DISTANCE_TO_TRAVEL_ACROSS_PLATFORM_ZONE;
    }

    @Override
    public double getDistanceToTravelToReachPlatformZone() {
        return SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_TO_TRAVEL_TO_REACH_PLATFORM_ZONE_EDGE_AFTER_TURN;
    }

    @Override
    public double getDistanceFromStartingPointToOtherPlatformZoneEdge() {
        return SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_STARTING_POINT_TO_OTHER_PLATFORM_ZONE_EDGE;
    }

    @Override
    public double getDegreeOfAngletoTurnToReachScaleSide() {
        return SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DEGREE_OF_ANGLE_TO_TURN_TO_REACH_SCALE_SIDE;
    }

    @Override
    public double getTotalDistanceToTravelToReachScaleSide() {
        return SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_TO_TRAVEL_TO_REACH_SCALE_SIDE;
    }

    @Override
    public double getDistanceFromRobotAfterTwoTurnsToNullTerritory() {
        return SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_TO_TRAVEL_TO_REACH_NULL_LINE;
    }
    //**************************************************************************************************************
    
/* Given FRC Manual Measurements*/
    //These distances is us starting on the left side of the field
    //all measurements are in inches or degrees if specified 
    //anything with // could be changed due to the actual field measure 
    
    //These are the measurements that need to be measured out before match.
    public static final double SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_PLATFORM_ZONE_EDGE_TO_BUMP = 66.75; //
    private static final double SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_ALLIANCE_STATION_TO_NULL_TERRITORY = 288.0; //
    private static final double SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_ALLIANCE_STATION_TO_AUTO_LINE = 120.0; //
    private static final double SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_ALLIANCE_STATION_TO_FAR_SIDE_OF_SWITCH = 196.0; //
    private static final double SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_ALLIANCE_STATION_TO_PLATFORM_EDGE = 261.47; //
    private static final double SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_ALLIANCE_STATION_TO_SCALE_SIDE = 299.65; //
    private static final double SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_BORDER_TO_PLATFORM_ZONE_EDGE = 95.25; //
    private static final double SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_BORDER_TO_EDGE_OF_ROBOT = 29.69; //
  //private static final double SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_NULL_BUMP_TO_AUTO_LINE = 204.0; //
    
    //**************************************************************************************************************
    
    private static final double SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_BORDER_TO_OTHER_EDGE_OF_ROBOT = SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_BORDER_TO_EDGE_OF_ROBOT + RobotMap.WIDTH_OF_BOT;
    private static final double SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_BORDER_TO_ROBOT_STARTING_POINT = SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_BORDER_TO_EDGE_OF_ROBOT + RobotMap.MIDDLE_OF_BOT_WIDTHWISE; //
    
    private static final double SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_SCALE_SIDE_TO_NULL_TERRITORY = SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_ALLIANCE_STATION_TO_SCALE_SIDE - SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_ALLIANCE_STATION_TO_NULL_TERRITORY;
    public static final double SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_FAR_SIDE_OF_SWITCH_TO_SCALE_SIDE = SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_ALLIANCE_STATION_TO_SCALE_SIDE - SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_ALLIANCE_STATION_TO_FAR_SIDE_OF_SWITCH;

    private static final double SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_LINE_SENSOR_TO_AUTO_LINE = SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_ALLIANCE_STATION_TO_AUTO_LINE - (RobotMap.LENGTH_OF_BOT - RobotMap.DISTANCE_LINE_SENSOR_IS_FROM_FRONT_BUMPER_OF_BOT);
   
    //**************************************************************************************************************
    //Scale auton where the bot is on the same side as the alliance scale and bot will be in the null territory
    //Keep in case the other scale auton doesn't work
    private static final double SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_NULL_BUMP_TO_AUTO_LINE = 204.0; //
    private static final double SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_TO_MOVE_INTO_NULL_BUMP = RobotMap.MIDDLE_OF_BOT_LENGTHWISE - RobotMap.DISTANCE_LINE_SENSOR_IS_FROM_FRONT_BUMPER_OF_BOT;
    private static final int SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DEGREE_OF_ANGLE_TO_TURN_IN_NULL_TERRITORY = 90;
    private static final double SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_TO_TRAVEL_BACKWARDS = SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_BORDER_TO_EDGE_OF_ROBOT - RobotMap.DIFFERENCE_BETWEEN_LENGTH_OF_ROBOT_AND_WIDTH_OF_ROBOT_AFTER_TURN; 
    private static final double SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_TO_TRAVEL_TO_REACH_SCALE_EDGE = FieldMapSideFurthestFromScoringTableMiddleQuadrant.SIDE_FURTHEST_FROM_SCORING_TABLE_MIDDLE_QUADRANT_DISTANCE_FROM_BORDER_TO_SCALE_EDGE - RobotMap.LENGTH_OF_BOT;
    
    //Scale auton where the bot is on the same side as the alliance scale and bot will turn at null territory line
    private static final double SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_AUTO_LINE_TO_NULL_TERRITORY = SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_ALLIANCE_STATION_TO_NULL_TERRITORY - SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_ALLIANCE_STATION_TO_AUTO_LINE;
    private static final double SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_SCALE_EDGE_TO_MIDDLE_OF_ROBOT = FieldMapSideFurthestFromScoringTableMiddleQuadrant.SIDE_FURTHEST_FROM_SCORING_TABLE_MIDDLE_QUADRANT_DISTANCE_FROM_BORDER_TO_SCALE_EDGE - SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_BORDER_TO_ROBOT_STARTING_POINT;
    private static final double SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_SCALE_EDGE_TO_MIDDLE_OF_ROBOT_SQUARED = SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_SCALE_EDGE_TO_MIDDLE_OF_ROBOT * SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_SCALE_EDGE_TO_MIDDLE_OF_ROBOT;
    private static final double SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_SCALE_SIDE_TO_NULL_TERRITORY_SQUARED = SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_SCALE_SIDE_TO_NULL_TERRITORY * SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_SCALE_SIDE_TO_NULL_TERRITORY;
    private static final double SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_TRAVEL_BACKWARDS = RobotMap.DISTANCE_LINE_SENSOR_IS_FROM_FRONT_BUMPER_OF_BOT;
    private static final double SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_TO_TRAVEL_TO_REACH_SCALE_CORNER = Math.sqrt(SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_SCALE_EDGE_TO_MIDDLE_OF_ROBOT_SQUARED + SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_SCALE_SIDE_TO_NULL_TERRITORY_SQUARED);
    private static final double SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DEGREE_OF_ANGLE_TO_REACH_IDEAL_STARTING_POINT_FROM_NULL_TERRITORY_LINE = -1 * Math.toDegrees(Math.atan(SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_SCALE_EDGE_TO_MIDDLE_OF_ROBOT / SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_SCALE_SIDE_TO_NULL_TERRITORY));
    
    //Scale auton where the bot is on the other side of the alliance scale
    private static final double SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_AUTO_LINE_TO_FAR_SIDE_OF_SWITCH = SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_ALLIANCE_STATION_TO_FAR_SIDE_OF_SWITCH - SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_ALLIANCE_STATION_TO_AUTO_LINE;
    private static final double SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_FAR_SIDE_OF_SWITCH_TO_PLATFORM_EDGE = SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_ALLIANCE_STATION_TO_PLATFORM_EDGE - SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_ALLIANCE_STATION_TO_FAR_SIDE_OF_SWITCH;
    public static final double SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_FAR_SIDE_OF_SWITCH_TO_PLATFORM_EDGE_HALVED = SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_FAR_SIDE_OF_SWITCH_TO_PLATFORM_EDGE / 2;
    private static final double SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_TO_TRAVEL_BEFORE_FIRST_TURN_FROM_AUTO_LINE = SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_AUTO_LINE_TO_FAR_SIDE_OF_SWITCH + SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_FAR_SIDE_OF_SWITCH_TO_PLATFORM_EDGE_HALVED + (RobotMap.MIDDLE_OF_BOT_LENGTHWISE - RobotMap.DISTANCE_LINE_SENSOR_IS_FROM_FRONT_BUMPER_OF_BOT); 
    private static final int SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DEGREE_OF_ANGLE_TO_TURN_TO_REACH_PLATFORM_ZONE = 90;
    private static final double SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_TO_TRAVEL_TO_REACH_PLATFORM_ZONE_EDGE_AFTER_TURN = (SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_BORDER_TO_PLATFORM_ZONE_EDGE - (SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_BORDER_TO_OTHER_EDGE_OF_ROBOT + RobotMap.DIFFERENCE_BETWEEN_LENGTH_OF_ROBOT_AND_WIDTH_OF_ROBOT_AFTER_TURN)) + RobotMap.DISTANCE_LINE_SENSOR_IS_FROM_FRONT_BUMPER_OF_BOT;
    private static final double SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_PLATFORM_ZONE_EDGE_TO_OTHER = SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_PLATFORM_ZONE_EDGE_TO_BUMP + FieldMapSideClosestToScoringTableRedQuadrant.SIDE_CLOSEST_TO_SCORING_TABLE_RED_QUADRANT_DISTANCE_FROM_PLATFORM_ZONE_EDGE_TO_BUMP;
    private static final double SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_TO_DRIVE_OUT_AFTER_PLATFORM_ZONE = RobotMap.WIDTH_OF_BOT - RobotMap.DISTANCE_LINE_SENSOR_IS_FROM_FRONT_BUMPER_OF_BOT; 
    private static final int SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DEGREE_OF_ANGLE_TO_TURN_TO_REACH_SCALE_SIDE = -90;
    private static final double SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_TO_TRAVEL_TO_REACH_SCALE_SIDE = FieldMapSideClosestToScoringTableBlueQuadrant.SIDE_CLOSEST_TO_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_FAR_SIDE_OF_SWITCH_TO_SCALE_SIDE - FieldMapSideClosestToScoringTableBlueQuadrant.SIDE_CLOSEST_TO_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_FAR_SIDE_OF_SWITCH_TO_PLATFORM_EDGE_HALVED;

  //**************************************************************************************************************

  //Measurements for line system
    //Use the constants these constants are set to to use for reset encoders
    //Different side scale auton
    //Reset encoders 3 times
    private static final double SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_TOTAL_DISTANCE_TO_TRAVEL_BEFORE_FIRST_TURN = SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_LINE_SENSOR_TO_AUTO_LINE + SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_TO_TRAVEL_BEFORE_FIRST_TURN_FROM_AUTO_LINE;
    private static final double SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_TOTAL_DISTANCE_TO_TRAVEL_ACROSS_PLATFORM_ZONE = SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_TO_TRAVEL_TO_REACH_PLATFORM_ZONE_EDGE_AFTER_TURN + SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_PLATFORM_ZONE_EDGE_TO_OTHER + SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_TO_DRIVE_OUT_AFTER_PLATFORM_ZONE;
    private static final double SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_STARTING_POINT_TO_OTHER_PLATFORM_ZONE_EDGE = SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_TO_TRAVEL_TO_REACH_PLATFORM_ZONE_EDGE_AFTER_TURN + SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_PLATFORM_ZONE_EDGE_TO_OTHER;
    //private static final double SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_TO_TRAVEL_TO_REACH_SCALE_SIDE = FieldMapSideFurthestFromScoringTableBlueQuadrant.SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_FAR_SIDE_OF_SWITCH_TO_SCALE_SIDE - FieldMapSideFurthestFromScoringTableBlueQuadrant.SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_FAR_SIDE_OF_SWITCH_TO_PLATFORM_EDGE_HALVED;
    private static final double SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_TO_TRAVEL_TO_REACH_NULL_LINE = SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_TO_TRAVEL_TO_REACH_SCALE_SIDE - SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_SCALE_SIDE_TO_NULL_TERRITORY;
    
    //Same side scale auton
    //Reset encoders once
    private static final double SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_TOTAL_DISTANCE_TO_TRAVEL_TO_REACH_NULL_TERRITORY_LINE = SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_LINE_SENSOR_TO_AUTO_LINE + SIDE_FURTHEST_FROM_SCORING_TABLE_BLUE_QUADRANT_DISTANCE_FROM_AUTO_LINE_TO_NULL_TERRITORY - RobotMap.DISTANCE_LINE_SENSOR_IS_FROM_FRONT_BUMPER_OF_BOT;
    //**************************************************************************************************************

}

